services:
  - type: web
    name: youtube-crawler
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py --proxy $PROXY_URL
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PROXY_URL
        sync: false
